const palette = {
  red: "#ED1C24",
  redDark: "#c01820",
  beige: "#a59d8b",
  beigeLight: "#d8d1c3",
  cream: "#FBF7F0",
  creamDeep: "#F4EFE5",
  white: "#FFFFFF",
  black: "#111111",
  textSecondary: "#6B6B6B",
  textMuted: "#9A9A9A",
  border: "#ECE6D8",
  shadow: "rgba(17,17,17,0.08)",
  gold: "#F5C542",
  // Dark theme
  darkBg: "#0F0F0D",
  darkSurface: "#181816",
  darkElevated: "#22211E",
  darkText: "#F8F5EE",
  darkTextSecondary: "#B8B1A3",
  darkTextMuted: "#8F887B",
  darkBorder: "#34322D",
  darkShadow: "rgba(0,0,0,0.4)",
};

export default {
  light: {
    text: palette.black,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    background: palette.cream,
    surface: palette.creamDeep,
    card: palette.white,
    elevated: palette.white,
    tint: palette.red,
    tabIconDefault: palette.beige,
    tabIconSelected: palette.red,
    border: palette.border,
    shadow: palette.shadow,
    iconBg: palette.white,
    iconColor: palette.black,
  },
  dark: {
    text: palette.darkText,
    textSecondary: palette.darkTextSecondary,
    textMuted: palette.darkTextMuted,
    background: palette.darkBg,
    surface: palette.darkSurface,
    card: palette.darkSurface,
    elevated: palette.darkElevated,
    tint: palette.red,
    tabIconDefault: palette.darkTextMuted,
    tabIconSelected: palette.red,
    border: palette.darkBorder,
    shadow: palette.darkShadow,
    iconBg: palette.darkElevated,
    iconColor: palette.darkText,
  },
};

export const Palette = palette;
